spring:
  application:
    name: reservafacil
  profiles:
    active: dev

jwt:
  public:
    key: classpath:app.pub
  private:
    key: classpath:app.key
  key_id: e51cdfc1-40d7-4551-be0d-0fb7ebd793f1
