spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reserva-facil
    username: toor
    password: pass@123
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
    defer-datasource-initialization: true